### ISSUE TITLE
TODO: Pull data for MMS list

### ISSUE THREAD

**Issue by KCollins** [KCollins/postdoc#1]
- [ ] Adapt THEMIS code to calculate new parameters (adjust CDAWeb pull - see notes below)
- [X] Verify dynamic pressure calculations
- [ ] Post to Zenodo: .pkl file, Jupyter notebook
- [ ] In magplots notebook, pull MMS data from Zenodo
- [ ] on Zenodo, add funding and related DOIs 
- [ ] Add link on Github issue (from magplots repo) to MMS zenodo page
- [ ] In magplots notebook, merge tables
- [ ] Create event plots for MMS data

### Notes on Parameters:

Revisit paper. Compare Fig 2 in Plaschke paper.

GSM Position: mms1_mec_r_gsm, from MMS1_MEC_SRVY_L2_EPHT89D:  https://cdaweb.gsfc.nasa.gov/pub/software/cdawlib/0SKELTABLES/mms1_mec_brst_l2_epht89d_00000000_v01.skt

Geographic:   "mms1_mec_r_geo"

Dist from bow shock, magnetopause, neutral sheet: These may not be easy to pull for MMS. Maybe leave these columns blank to ensure compatibility with THEMIS dataframe.

https://cdaweb.gsfc.nasa.gov/pub/software/cdawlib/0SKELTABLES/mms1_fpi_fast_l2_des-dist_00000000_v01.skt
> "MMS1_FPI_FAST_L2_DIS-DIST" or "MMS1_FPI_FAST_L2_DIS-MOM"

Moments:
> MMS1_FPI_FAST_L2_DIS-MOMS https://cdaweb.gsfc.nasa.gov/pub/software/cdawlib/0SKELTABLES/mms1_fpi_fast_l2_des-moms_00000000_v01.skt

https://cdaweb.gsfc.nasa.gov/pub/software/cdawlib/0SKELTABLES/mms1_fpi_fast_l2_dis-moms_00000000_v01.skt
> MMS1 FPI/DIS ion number density during this survey
> 
> (    "CATDESC"     CDF_CHAR     { "---> (no error bars displayed) MMS1 " -
                                 "FPI/DIS ion number density during this" -
                                 " survey" })
> 
> MMS1 FPI/DIS ion bulk-velocity vector in GSE during this survey
